id: P198A9E55
initial_creation_type: ocr
source_metadata:
  volumes:
    c68eacbcc74846aebe4806162e458e39:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: ཐེག་པ་ཆེན་པོའི་ལམ་གྱི་སྒྲུབ་ཐབས་ཤིན་ཏུ་བསྡུས་པ།
      total_pages: 1902
      volume_number: 64
